apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: canes-api
  name: canes-api-config
  namespace: interstellar
data:
  APP_NAME: "Lumen"
  APP_ENV: "local"
  APP_KEY: ""
  APP_DEBUG: "true"
  APP_URL: "http://localhost"
  APP_TIMEZONE: "UTC"
  LOG_CHANNEL: "stack"
  LOG_SLACK_WEBHOOK_URL: ""
  DB_CONNECTION: "mysql"
  DB_HOST: "172.22.4.20"
  DB_PORT: "3306"
  DB_DATABASE: "canes"  
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
  JWT_TTL: "4320"