apiVersion: v1
kind: Service
metadata:
  labels:
    app: canes-api
  name: canes-api-service
  namespace: interstellar
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30358
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: canes-api
  sessionAffinity: None
  type: NodePort